spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config, file:./config, file:./config

server:
  port: 8159
